version: '3.8'

services:
  db:
    image: postgres:16
    container_name: bot_db
    restart: always
    environment:
      POSTGRES_DB: botdb
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: botpass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: townguide_bot
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/botdb
      SPRING_DATASOURCE_USERNAME: botuser
      SPRING_DATASOURCE_PASSWORD: botpass
    ports:
      - "8080:8080"

volumes:
  db_data:
